apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-webui-deployment
  namespace: open-webui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-webui
  template:
    metadata:
      labels:
        app: open-webui
    spec:
      containers:
      - name: open-webui
        image: ghcr.io/open-webui/open-webui:main
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "500m"
            memory: "500Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
        env:
        - name: OLLAMA_BASE_URL
          value: "http://ollama-service.open-webui.svc.cluster.local:11434"
        - name: ENABLE_RAG_WEB_SEARCH
          value: "true"
        - name: ENABLE_RAG_LOCAL_WEB_FETCH
          value: "true"
        - name: WEBUI_URL
          value: "http://0.0.0.0:8080"
        tty: true
        volumeMounts:
        - name: webui-volume
          mountPath: /app/backend/data
      - name: sovereign-agent-platform
        image: sovereign-platform:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "1000m"
            memory: "1Gi"
          limits:
            cpu: "2000m"
            memory: "2Gi"
        env:
        - name: PYTHONPATH
          value: "/app"
        - name: OPENWEBUI_INTEGRATION
          value: "true"
        - name: LOG_LEVEL
          value: "INFO"
        - name: WEBUI_URL
          value: "http://localhost:8080"
        volumeMounts:
        - name: platform-volume
          mountPath: /app/data
        - name: platform-logs
          mountPath: /app/logs
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: webui-volume
        persistentVolumeClaim:
          claimName: open-webui-pvc
      - name: platform-volume
        persistentVolumeClaim:
          claimName: sovereign-platform-pvc
      - name: platform-logs
        persistentVolumeClaim:
          claimName: sovereign-logs-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: sovereign-platform-service
  namespace: open-webui
spec:
  selector:
    app: open-webui
  ports:
  - name: platform-api
    port: 8000
    targetPort: 8000
  - name: webui
    port: 8080
    targetPort: 8080
  type: LoadBalancer

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sovereign-platform-pvc
  namespace: open-webui
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sovereign-logs-pvc
  namespace: open-webui
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
